--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-01-04 16:26:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16396)
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    company_size character varying(255),
    description character varying(1000) NOT NULL,
    field_of_work character varying(255) NOT NULL,
    location character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    website_link character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.companies OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16395)
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16403)
-- Name: student_hobbies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_hobbies (
    student_id bigint NOT NULL,
    hobbies character varying(255)
);


ALTER TABLE public.student_hobbies OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16406)
-- Name: student_known_languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_known_languages (
    student_id bigint NOT NULL,
    known_languages character varying(255)
);


ALTER TABLE public.student_known_languages OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16409)
-- Name: student_past_experience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_past_experience (
    student_id bigint NOT NULL,
    past_experience character varying(255)
);


ALTER TABLE public.student_past_experience OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16412)
-- Name: student_projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_projects (
    student_id bigint NOT NULL,
    projects character varying(255)
);


ALTER TABLE public.student_projects OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16415)
-- Name: student_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_skills (
    student_id bigint NOT NULL,
    skills character varying(255)
);


ALTER TABLE public.student_skills OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16419)
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    age integer NOT NULL,
    current_university_name character varying(255) NOT NULL,
    degree character varying(255) NOT NULL,
    expected_graduation_date character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    github_link character varying(255),
    linkedin_link character varying(255),
    location character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.students OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16418)
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16427)
-- Name: universities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.universities (
    id bigint NOT NULL,
    location character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.universities OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16426)
-- Name: universities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.universities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.universities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16435)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    user_type character varying(255) NOT NULL,
    CONSTRAINT users_user_type_check CHECK (((user_type)::text = ANY ((ARRAY['STUDENT'::character varying, 'COMPANY'::character varying, 'UNIVERSITY'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16434)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4732 (class 2606 OID 16402)
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- TOC entry 4736 (class 2606 OID 16425)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 4734 (class 2606 OID 16444)
-- Name: companies uk5xg6ed73n32iai9psir68pia9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT uk5xg6ed73n32iai9psir68pia9 UNIQUE (user_id);


--
-- TOC entry 4744 (class 2606 OID 16450)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4740 (class 2606 OID 16448)
-- Name: universities ukfao2danoqmo1poe7v0pp7ptu7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT ukfao2danoqmo1poe7v0pp7ptu7 UNIQUE (user_id);


--
-- TOC entry 4738 (class 2606 OID 16446)
-- Name: students ukg4fwvutq09fjdlb4bb0byp7t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id);


--
-- TOC entry 4742 (class 2606 OID 16433)
-- Name: universities universities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_pkey PRIMARY KEY (id);


--
-- TOC entry 4746 (class 2606 OID 16442)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 16456)
-- Name: student_hobbies fk3jcm5vj5iefvg9yt2tgqmxnbj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_hobbies
    ADD CONSTRAINT fk3jcm5vj5iefvg9yt2tgqmxnbj FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4747 (class 2606 OID 16451)
-- Name: companies fk9l5d0fem75e59uwf9upwuf9du; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT fk9l5d0fem75e59uwf9upwuf9du FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4754 (class 2606 OID 16486)
-- Name: universities fkbwoq7tf4qcb4naga75kll143m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT fkbwoq7tf4qcb4naga75kll143m FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4753 (class 2606 OID 16481)
-- Name: students fkdt1cjx5ve5bdabmuuf3ibrwaq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4751 (class 2606 OID 16471)
-- Name: student_projects fkk18t5hj8t26ljx8w4j3phdjde; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_projects
    ADD CONSTRAINT fkk18t5hj8t26ljx8w4j3phdjde FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4749 (class 2606 OID 16461)
-- Name: student_known_languages fkmr7gvlmnodnr0tsdoxlq6unql; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_known_languages
    ADD CONSTRAINT fkmr7gvlmnodnr0tsdoxlq6unql FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4752 (class 2606 OID 16476)
-- Name: student_skills fkovs9ju1ccjg7kq2m3tct9oh1y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_skills
    ADD CONSTRAINT fkovs9ju1ccjg7kq2m3tct9oh1y FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4750 (class 2606 OID 16466)
-- Name: student_past_experience fkta1l5447eic1t37hc0st1n81i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_past_experience
    ADD CONSTRAINT fkta1l5447eic1t37hc0st1n81i FOREIGN KEY (student_id) REFERENCES public.students(id);


-- Completed on 2025-01-04 16:26:34

--
-- PostgreSQL database dump complete
--

